// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/handikacatur/jobs-api/cmd/config"
	"github.com/handikacatur/jobs-api/internal/job/repository/gorm"
	"github.com/handikacatur/jobs-api/internal/job/service"
)

// Injectors from wire.go:

func InitService() service.JobServiceProvider {
	configConfig := config.InitConfig()
	databaseConfig := configConfig.Database
	db := initDatabase(databaseConfig)
	jobRepositoryProvider := gorm.NewJobRepository(db)
	jobServiceConfig := service.JobServiceConfig{
		JobRepo: jobRepositoryProvider,
	}
	jobServiceProvider := service.NewJobService(jobServiceConfig)
	return jobServiceProvider
}

// wire.go:

var (
	sets = wire.NewSet(config.InitConfig, wire.FieldsOf(new(config.Config), "Database"), initDatabase)
)
